# Generated by Django 3.0 on 2020-12-04 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nf', models.CharField(max_length=45, verbose_name='Numero NF')),
                ('industria', models.CharField(max_length=40, verbose_name='Industria')),
                ('dia_descarga', models.DateField(verbose_name='Dia da descarga')),
                ('status', models.CharField(choices=[('liberado', 'Liberado'), ('aguardando', 'Aguardando')], max_length=15, verbose_name='Status')),
                ('tipo_entrada', models.CharField(blank=True, max_length=20)),
                ('Produto', models.CharField(blank=True, max_length=40)),
                ('QTD', models.CharField(blank=True, max_length=10)),
                ('UN', models.CharField(blank=True, max_length=10)),
                ('movimentacao', models.CharField(blank=True, max_length=20)),
                ('frete', models.CharField(blank=True, max_length=10)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('box', models.CharField(blank=True, max_length=20, verbose_name='Box')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
