# Generated by Django 3.1.3 on 2020-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nf', models.CharField(max_length=20, verbose_name='Numero NF')),
                ('industria', models.CharField(max_length=20, verbose_name='Industria')),
                ('dia_descarga', models.DateField(verbose_name='Dia da descarga')),
                ('status', models.CharField(choices=[('liberado', 'Liberado'), ('aguardando', 'Aguardando')], max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
