# Generated by Django 3.0 on 2020-12-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_box_tipo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='name1',
            field=models.CharField(default='2', max_length=20, verbose_name='Nome do Box'),
            preserve_default=False,
        ),
    ]
