# Generated by Django 3.1.3 on 2020-11-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carga_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.AlterField(
            model_name='carga',
            name='industria',
            field=models.CharField(max_length=40, verbose_name='Industria'),
        ),
        migrations.AlterField(
            model_name='carga',
            name='numero_nf',
            field=models.CharField(max_length=40, verbose_name='Numero NF'),
        ),
    ]
