# Generated by Django 3.1.3 on 2020-11-27 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201127_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='box',
            name='box_name',
            field=models.CharField(default='Box', max_length=20, verbose_name='name'),
        ),
    ]
