# Generated by Django 3.0 on 2021-01-27 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20210127_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='name1',
        ),
        migrations.AddField(
            model_name='carga',
            name='is_ERP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carga',
            name='numero_transacao',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='carga',
            name='user_ERP',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='carga',
            name='valor_carga',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='carga',
            name='UN',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='carga',
            name='observacao',
            field=models.CharField(blank=True, max_length=500),
        ),
        
       
    ]
