# Generated by Django 3.1.3 on 2020-11-27 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201127_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.box'),
            preserve_default=False,
        ),
    ]
