# Generated by Django 3.1.2 on 2021-03-01 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20210127_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='cor',
            field=models.CharField(default='1', max_length=4, verbose_name='cor'),
            preserve_default=False,
        )
    ]
