# Generated by Django 3.1.3 on 2020-11-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carga_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='box',
            name='box_name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
    ]
