# Generated by Django 3.1.3 on 2020-11-27 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201127_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.box'),
        ),
    ]
