# Generated by Django 3.1.3 on 2020-11-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201127_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.box'),
        ),
    ]
