# Generated by Django 3.1.3 on 2020-11-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201127_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='box',
            field=models.CharField(max_length=20, null=True, verbose_name='Box'),
        ),
    ]
