# Generated by Django 3.1.3 on 2020-11-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201127_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='box',
            field=models.CharField(default=' ', max_length=20, verbose_name='Box'),
        ),
    ]
